config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
    # resources :reviews, only: :create
  end
  resources :bookmarks, only: :destroy
  # resources :reviews, only: :destroy
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: {scope: :list_id, message: "is already in the list"}
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list

  def new
    @bookmark = Bookmark.new
    # @list = List.find(params[:list_id])
  end

  def create
    # @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    # @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to lists_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @bookmarks = @list.bookmarks
    @movies = @list.movies
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_modal.html.erb
<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a movie to your <%= list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>

      <%# <%= simple_form_for [list, bookmark] do |f| %> %>
        <%# <div class="modal-body"> %>
          <%# <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", #input_html: { data: { controller: "tom-select" } }%> %>
          <%# <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
        <%# </div> %>
        <%# <div class="modal-footer"> %>
          <%# <%= f.submit "Add movie", class: "btn btn-flat" %> %>
          <%# <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button> %>
        <%# </div> %>
      <%# <% end %> %>
    </div>
  </div>
</div>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-grey">
    <h1>Create a new Bookmark to the list</h1>
    <h3 class="typed-js" data-controller="typed-js"></h3>
  </div>
</div>

<div class="container py-5">
  <div class="d-flex align-items-center mb-3">
    <%= link_to "create a new list", new_list_path, class: "btn btn-flat" %>
    <%= link_to "return to all lists", lists_path, class: "btn btn-flat" %>
  </div>
  <div>
    <h1>New Bookmark</h1>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.input :comment %>
      <%= f.association :list %>
      <%= f.association :movie %>
      <%= f.submit "Submit Bookmark", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<%# <h1>List of Movies</h1>
<%= link_to "create list", new_list_path %>
<%# <ul>
  <% @lists.each do |list| %>
  <%# <li><%= link_to list.name, list_path(list)</li> %>
  <%# <% end %>
<%# </ul> %>

<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-grey">
    <h1>Save any kind of movies</h1>
    <h3 class="typed-js" data-controller="typed-js"></h3>
  </div>
</div>
<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">My Lists</h3>
    <%= link_to "Create a movie list", new_list_path, class: "btn btn-flat" %>
  </div>
  <%# <%= cl_image_tag("dcbeavwkct4czttbhxpr", width: 400, height: 300, crop: :fill) %>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="co-12 col-sm-6 col-md-4 mb-3">
        <%= link_to list_path(list), class:"text-decoration-none" do %>
          <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('list_background.jpg') %>)">
            <%= list.name %>
            <%= link_to "Create a bookmark", new_list_bookmark_path(list), class: "btn btn-flat text-white" %>
            <% if list.photo.present? %>
              <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Create a new List</h1>
<%= link_to "return to list", lists_path %>

<h1>New List</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit List", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<ul>
  <% @bookmarks.each do |bookmark| %>
    <li>
      <%= bookmark.movie.title %>
      <%= bookmark.comment %>
      <%= link_to "delete this bookmark from this list", bookmark_path(bookmark),
            data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{bookmark.movie.title} from your #{@list.name} list"}, class: 'text-danger' %>
    </li>
  <% end %>
</ul>

<div class="d-flex align-items-center mb-3">
  <ul>
    <li><%= link_to "Add a bookmark to this list", new_list_bookmark_path(@list) %></li>
    <%= link_to "return to all lists", lists_path, class: "btn btn-flat" %>
  </ul>
</div>

<ul>
  <li>
    <%= link_to "delete this list", list_path(@list), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
  </li>
</ul>

<%= render "bookmarks/modal", list: @list, bookmark: @bookmark %>

<div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>